# Generated by Django 2.0.3 on 2020-06-20 10:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='extra1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='extra2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='extra3',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.ShopCart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='placing_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 10, 26, 28, 445773, tzinfo=utc)),
        ),
    ]
