# Generated by Django 2.0.3 on 2020-06-20 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200620_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placing_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
