# Generated by Django 2.0.3 on 2020-06-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200620_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.AddField(
            model_name='shopcart',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
