# Generated by Django 2.0.3 on 2020-06-21 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200621_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='number',
        ),
    ]
