# Generated by Django 2.0.3 on 2020-06-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200621_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='trait',
            field=models.CharField(blank=True, choices=[('SMALL', 'Small'), ('LARGE', 'Large'), ('ADDITION', 'Addition')], max_length=1, null=True),
        ),
    ]
