# Generated by Django 2.0.3 on 2020-06-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200621_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='trait',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('L', 'Large'), ('A', 'Addition')], max_length=1, null=True),
        ),
    ]
