# Generated by Django 2.0.3 on 2020-06-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200621_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcart',
            name='order_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_number', to='orders.Order'),
        ),
    ]
